MODEL:
  META_ARCHITECTURE: "RetinaNet"
  WEIGHT: "catalog://ImageNetPretrained/FBResNeXt/X-101-64x4d"
  RPN_ONLY: True
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    NMS_THRESH: 0.5
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)  # coco_test_dev
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960,) # (640, 672, 704, 736, 768, 800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
TEST:
  IMS_PER_BATCH: 48
  DETECTIONS_PER_IMG: 100
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 32
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2500
RETINANET:
  RETINANET_ON: True
  NUM_CLASSES: 81
  PRIOR_PROB: 0.02
  SCALES_PER_OCTAVE: 3
  STRADDLE_THRESH: -1
FREEANCHOR:
  IA_ON: True
  IA_FEAT: True
  IA_FEAT_TYPE: 0
  MASK_TYPE: 0
  IA_TYPE: 5 
  FREEANCHOR_ON: True
  PRE_ANCHOR_TOPK: 50
  BBOX_THRESHOLD: 0.6
  BBOX_REG_WEIGHT: 0.75
  FOCAL_LOSS_ALPHA: 0.5
  FOCAL_LOSS_GAMMA: 2.0
OUTPUT_DIR: outputs/mal_X-101-FPN_j2x_FIA_T5_v3
